# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               TecnoPalma BLOG
tagline:             ''
url:                 
description:         'Un lloc de tot un poc.'
paginate:            10
highlighter:         null

# About/contact
author:
  name:              'Sergi navas'
  email:             'sergi@tecnopalma.com'
  url:               ''
  github:            'https://github.com/s3rgi'
  twitter:           'https://twitter.com/s3rgi'

# Custom vars
version:             1.1.0

github:
  repo:              https://github.com/s3rgi/s3rgi.github.io

excerpt_separator:   <!--more-->

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - output
  - Gruntfile.js
  - package.json
  - tasks.py
  - node_modules
  - dist
